//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization.databaseSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletingOfTheWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompletingOfTheWork()
        {
            this.Work = new HashSet<Work>();
        }
    
        public int ID { get; set; }
        public int NomerJob { get; set; }
        public string NameWork { get; set; }
        public int Laboriousness { get; set; }
        public Nullable<System.DateTime> DataOfComplite { get; set; }
        public System.DateTime PlannedEndDate { get; set; }
        public int Readiness { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work> Work { get; set; }

    }
}
