//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization.databaseSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int ID { get; set; }
        public int JobNomer { get; set; }
        public int Worker { get; set; }
    
        public virtual CompletingOfTheWork CompletingOfTheWork { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
